# Generated by Django 2.1.5 on 2019-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severe_team', models.CharField(choices=[('DOTA 2', 'DOTA 2')], max_length=10)),
                ('opponent', models.CharField(max_length=50)),
                ('league', models.CharField(choices=[('VS Gaming', 'VS Gaming')], max_length=20, null=True)),
                ('division', models.CharField(choices=[('Premier', 'Premier'), ('First', 'First'), ('Second', 'Second')], max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('match_result', models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=10)),
                ('leg', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], max_length=1)),
                ('match_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
