# Generated by Django 2.1.5 on 2019-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pla', models.CharField(max_length=100)),
                ('about', models.CharField(default='General', max_length=20)),
                ('hook', models.TextField(max_length=300)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
