# Generated by Django 2.1.5 on 2019-01-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='DOTA2',
        ),
    ]
