# Generated by Django 2.1.5 on 2019-01-18 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20190118_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DOTA2',
            new_name='Dota',
        ),
    ]
