# Generated by Django 2.1.5 on 2019-01-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190118_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dota',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
