# Generated by Django 2.1.5 on 2019-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190118_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pla', models.CharField(max_length=100)),
                ('about', models.CharField(default='General', max_length=20)),
                ('hook', models.TextField(max_length=300)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
