# Generated by Django 2.1.5 on 2019-01-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_csgo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csgo',
            options={'verbose_name_plural': 'Counter-Strike: Global Offensive'},
        ),
        migrations.AlterModelOptions(
            name='dota',
            options={'verbose_name_plural': 'Dota 2'},
        ),
    ]
