# Generated by Django 2.1.5 on 2019-01-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20190118_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSGO',
            new_name='CSGO_Player',
        ),
        migrations.RenameModel(
            old_name='Dota',
            new_name='Dota_2_Player',
        ),
    ]
