# Generated by Django 2.1.5 on 2019-01-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20190118_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dota_2_Player',
            new_name='Dota2Player',
        ),
    ]
