# Generated by Django 2.1.5 on 2019-01-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20190118_1529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSGO_Player',
            new_name='CounterStrikePlayer',
        ),
    ]
