# Generated by Django 2.1.5 on 2019-01-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20190118_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='hook',
            new_name='PlayerBio',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='Pla',
            new_name='PlayerName',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='thumb',
            new_name='PlayerPicture',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='about',
            new_name='PlayerPosition',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='hook',
            new_name='PlayerBio',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Pla',
            new_name='PlayerName',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='thumb',
            new_name='PlayerPicture',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='about',
            new_name='PlayerPosition',
        ),
    ]
