# Generated by Django 2.1.5 on 2019-01-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20190118_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='PlayerBio',
            new_name='Bio',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='PlayerBio',
            new_name='Bio',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='PlayerPicture',
            new_name='Picture',
        ),
        migrations.RemoveField(
            model_name='counterstrikeplayer',
            name='PlayerName',
        ),
        migrations.RemoveField(
            model_name='counterstrikeplayer',
            name='PlayerPicture',
        ),
        migrations.RemoveField(
            model_name='counterstrikeplayer',
            name='PlayerPosition',
        ),
        migrations.RemoveField(
            model_name='dota2player',
            name='PlayerName',
        ),
        migrations.RemoveField(
            model_name='dota2player',
            name='PlayerPosition',
        ),
        migrations.AddField(
            model_name='counterstrikeplayer',
            name='Name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='counterstrikeplayer',
            name='Picture',
            field=models.ImageField(blank=True, default='PPdefault.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='counterstrikeplayer',
            name='Position',
            field=models.CharField(default='Position', max_length=20),
        ),
        migrations.AddField(
            model_name='dota2player',
            name='Name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='dota2player',
            name='Position',
            field=models.CharField(default='Position', max_length=20),
        ),
    ]
