# Generated by Django 2.1.5 on 2019-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20190118_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstrikeplayer',
            name='CounterStrikeStats',
            field=models.CharField(default='CSGO STATS', max_length=400),
        ),
        migrations.AddField(
            model_name='counterstrikeplayer',
            name='SteamID',
            field=models.CharField(default='Steam ID', max_length=300),
        ),
        migrations.AddField(
            model_name='dota2player',
            name='Dotabuff',
            field=models.CharField(default='DOTABUFF', max_length=400),
        ),
        migrations.AddField(
            model_name='dota2player',
            name='SteamID',
            field=models.CharField(default='Steam ID', max_length=300),
        ),
        migrations.AlterField(
            model_name='counterstrikeplayer',
            name='Name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='dota2player',
            name='Picture',
            field=models.ImageField(blank=True, default='PPdefault.png', upload_to=''),
        ),
    ]
