# Generated by Django 2.1.5 on 2019-01-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20190118_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterstrikeplayer',
            name='Picture',
            field=models.ImageField(blank=True, default='PPdefault.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='dota2player',
            name='Picture',
            field=models.ImageField(blank=True, default='PPdefault.jpg', upload_to=''),
        ),
    ]
