# Generated by Django 2.1.5 on 2019-01-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20190118_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstrikeplayer',
            name='Surname',
            field=models.CharField(default='Surname', max_length=100),
        ),
        migrations.AddField(
            model_name='dota2player',
            name='Surname',
            field=models.CharField(default='Surname', max_length=100),
        ),
    ]
