# Generated by Django 2.1.5 on 2019-01-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20190121_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='CounterStrikeStats',
            new_name='counterstrikestats',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='Picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='Position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='SteamID',
            new_name='steamID',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='counterstrikeplayer',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Dotabuff',
            new_name='dotabuff',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Position',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='SteamID',
            new_name='steamID',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Surname',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='dota2player',
            old_name='Username',
            new_name='username',
        ),
    ]
