# Generated by Django 2.1.5 on 2019-01-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190116_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.CharField(default='General', max_length=20),
        ),
    ]
