# Generated by Django 2.1.5 on 2019-01-18 07:12

from django.db import migrations
import precise_bbcode.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190118_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hook',
            field=precise_bbcode.fields.BBCodeTextField(default=None, no_rendered_field=True),
        ),
    ]
