# Generated by Django 2.1.5 on 2019-01-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190118_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hook',
            field=models.TextField(max_length=300),
        ),
    ]
