# Generated by Django 2.1.5 on 2019-01-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('league', models.CharField(choices=[('VS Gaming', 'VS Gaming')], max_length=20, null=True)),
                ('division', models.CharField(choices=[('Premier', 'Premier'), ('First', 'First'), ('Second', 'Second')], max_length=10)),
                ('leg', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], max_length=1)),
                ('placed', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Achievements',
            },
        ),
    ]
