# Generated by Django 2.1.5 on 2019-01-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_auto_20190130_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievement',
            new_name='DotaAchievement',
        ),
        migrations.AlterModelOptions(
            name='dotaachievement',
            options={'verbose_name_plural': 'Dota Achievements'},
        ),
    ]
