# Generated by Django 2.1.5 on 2019-01-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190111_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('VS League', 'VS League')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='division',
            field=models.CharField(choices=[('Premier', 'Premier'), ('First', 'First'), ('Second', 'Second')], max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='leg',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_result',
            field=models.CharField(choices=[('W', 'Won'), ('L', 'Lost')], max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='severe_team',
            field=models.CharField(choices=[('DOTA 2', 'DOTA 2')], max_length=10),
        ),
    ]
