# Generated by Django 2.1.5 on 2019-01-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190111_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('VS Gaming', 'VS Gaming')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_result',
            field=models.CharField(choices=[('Won', 'Won'), ('Lost', 'Lost')], max_length=10),
        ),
    ]
