# Generated by Django 2.1.5 on 2019-01-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190115_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
