# Generated by Django 2.1.5 on 2019-01-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
